import Head from "next/head";
import Image from "next/image";
import { Navbar, Trending } from "../components/index";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Entertainment web app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <Navbar />
        <Trending />
      </div>
    </div>
  );
}
